/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BpiAlert {
        "icon": string;
        "message": string;
        "show": boolean;
    }
    interface BpiButton {
        "disabled": boolean;
        "icon": string;
    }
    interface BpiLoader {
    }
}
export interface BpiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBpiButtonElement;
}
declare global {
    interface HTMLBpiAlertElement extends Components.BpiAlert, HTMLStencilElement {
    }
    var HTMLBpiAlertElement: {
        prototype: HTMLBpiAlertElement;
        new (): HTMLBpiAlertElement;
    };
    interface HTMLBpiButtonElement extends Components.BpiButton, HTMLStencilElement {
    }
    var HTMLBpiButtonElement: {
        prototype: HTMLBpiButtonElement;
        new (): HTMLBpiButtonElement;
    };
    interface HTMLBpiLoaderElement extends Components.BpiLoader, HTMLStencilElement {
    }
    var HTMLBpiLoaderElement: {
        prototype: HTMLBpiLoaderElement;
        new (): HTMLBpiLoaderElement;
    };
    interface HTMLElementTagNameMap {
        "bpi-alert": HTMLBpiAlertElement;
        "bpi-button": HTMLBpiButtonElement;
        "bpi-loader": HTMLBpiLoaderElement;
    }
}
declare namespace LocalJSX {
    interface BpiAlert {
        "icon"?: string;
        "message"?: string;
        "show"?: boolean;
    }
    interface BpiButton {
        "disabled"?: boolean;
        "icon"?: string;
        "onEeHandler"?: (event: BpiButtonCustomEvent<string>) => void;
    }
    interface BpiLoader {
    }
    interface IntrinsicElements {
        "bpi-alert": BpiAlert;
        "bpi-button": BpiButton;
        "bpi-loader": BpiLoader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bpi-alert": LocalJSX.BpiAlert & JSXBase.HTMLAttributes<HTMLBpiAlertElement>;
            "bpi-button": LocalJSX.BpiButton & JSXBase.HTMLAttributes<HTMLBpiButtonElement>;
            "bpi-loader": LocalJSX.BpiLoader & JSXBase.HTMLAttributes<HTMLBpiLoaderElement>;
        }
    }
}
